spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hww?serverTimezone=CTT&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver


# 配置 MyBatis
mybatis:
  mapper-locations: classpath:dao/*
  configuration:
    map-underscore-to-camel-case: true