POST http://localhost:8080/Student/getStudentsInfo
Content-Type: application/json

{
  "age": "20"
}
###
POST http://localhost:8080/catalogue/getStudentsInfo
Content-Type: application/json

{
"age": "20"
}
